apiVersion: apps/v1
kind: Deployment
metadata:
  name: mounika-monitored-app
  namespace: default
  labels:
    app: mounika-monitored-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mounika-monitored-app
  template:
    metadata:
      labels:
        app: mounika-monitored-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: mounika-monitored-app
          image: mounika-monitored-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"